name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.1.1
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
